version: "2"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: heliumlabs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres