version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile-app
    volumes:
      - coinbin:/coinbin
    depends_on:
      - daemon
    command: bash -c "cp /coinbin/helium* /usr/local/bin/ && node index.js"
    ports:
      - "3000:3000"
    env_file: ../.env
    environment:
      - DB_HOST=db # override for docker-compose internal network
      - MAILGUN_API_KEY # secret, set manually with $ export MAILGUN_API_KEY=[api-key]
      - MAILGUN_DOMAIN # secret, set manually with $ export MAILGUN_DOMAIN=[domain]

  daemon:
    build:
      context: .
      dockerfile: ./Dockerfile-daemon
    volumes:
      - coinbin:/coinbin
    ports:
      - 8332:8332
    command: bash -c "cp /usr/local/bin/helium* /coinbin && /usr/local/bin/heliumd"

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: heliumlabs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  coinbin: